language: php
php:
  - "5.5"

# whitelist (l8r)
#branches:
#  only:
#    - dev

 before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: laravel/vendor/bin/phpunit
